project_name: "Holgerdocs"
before:
  hooks:
    - go mod tidy
builds:
  - id: "holgerdocs"
    main: ./cmd
    binary: holgerdocs
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true

release:
  mode: replace
  name_template: "{{.ProjectName}}-{{.Version}}"
  header: |
    ## Hoglerdocs release {{ .Tag }}