name: "Linting Code Base"

on: [push, pull_request]

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      name: "Checkout Code"

    - uses: actions/setup-go@v3
      name: "Install Golang"
      with:
       go-version: ">=1.18"

    - uses: golangci/golangci-lint-action@v3
      name: golangci-lint
      with:
        args: --config .golangci.yml